# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: 20
      - run: yarn --immutable
      # - run: yarn test
      - run: yarn build
      - run: yarn pack
      - run: ls dist*
      - run: tar xvzf package.tgz
      - run: npx publint --strict

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: yarn --immutable
      - run: yarn build
      - run: yarn pack
      - name: Configure GitHub Packages Auth
        run: |
          yarn npm logout
          echo "@mause:registry=https://npm.pkg.github.com/" > .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn config
      - run: cat .npmrc || echo 'no'
      - run: cat .yarnrc.yml || echo 'no'
      - run: cat ~/.yarnrc.yml || echo 'no'
      - run: cat ~/.npmrc || echo 'no'
      - run: yarn npm whoami
      - run: yarn npm publish --access restricted --tag latest --dry-run
      - run: yarn npm publish --access restricted --tag latest
        if: github.event_name == 'release'
